# Seeded by devenv. Edit freely; devenv keeps your changes.
---
format:
  line_width: 100
  tab_size: 2
  dangle_parens: true
  command_case: lower
  keyword_case: upper
markup:
  enable_markup: false
